### ISSUE TITLE
Example karma setup?

### ISSUE THREAD

**Issue by teddyhwang** [benbria/karma-coffee-coverage#1]
I'm looking to setup code coverage for my project that has browserify + coffeeify and this looks like the right tool to do it. I'm a little confused by how this is supposed to work. Could you give an example karma config file that shows how this integrates with browserify-coffee-coverage and karma-coverage?

**Comment by calvinwiebe** [comment]
Sure thing! There is a blurb about it [here](https://github.com/benbria/coffee-coverage/blob/master/docs/HOWTO-browserify-karma.md). 

`browserify-coffee-coverage` is the first step; it will instrument your final bundle with coverage instrumentation. Use it in place of `coffeeify`. You could then just include your bundle in the `files` array of your karma config and turn on `karma-coverage`, and you'd get a report on that bundle. However, you wouldn't be accounting for all of your sources that are *not* in your bundle. This is where `karma-coffee-coverage` comes in. It will create a supplementary `.js` file that is a blank coverage object representing all of your sources. 

Here is an example of building your bundle programmatically with browserify and `browserify-coffee-coverage`:

```javascript
var coverage = require('browserify-coffee-coverage');
var b = browserify();
b.add('./foo.coffee');
// don't create initialization code, as we are generating it ourselves with `karma-coffee-coverage`
var options = { noInit: false };
b.transform(coverage, options);
b.bundle();
```

Here is an example `karma.config.coffee` that loads the above built and instrumented bundle (assuming we built `mainBundle.js`). It has no reference to `browserify-coffee-coverage`, as that is part of the build step. 

```coffee-script
module.exports = (config) ->
  config.set

    basePath: ''

    # tell karma to run `karma-coffee-coverage`
    frameworks: ['coffee-coverage']

    # configure `karma-coffee-coverage`. Tell it your base directory of your sources, where to put the built 
    # coverage initialization file, and which style of instrumentation (supported by `coffee-coverage`)
    coffeeCoverage:
        framework:
            initAllSources: true
            sourcesBasePath: 'assets'
            dest: 'build/coverage-init.js'
            instrumentor: 'istanbul'

    # include your initial blank coverage file generated by `karma-coffee-coverage` as well as the
    # instrumented bundle we built above `mainBundle.js`
    files: [
        'build/coverage-init.js'
        'build/mainBundle.js'
    ]

    # tell karma to report with `karma-coverage`. 
    reporters: [
        'progress'
        'coverage'
    ]

    # configure `karma-coverage`
    coverageReporter:
        dir : 'coverage/'
        subdir: '.'
        reporters: [
            { type: 'lcov', subdir: 'client-lcov' }
            { type: 'json', subdir: '.', file: 'coverage-coffee-client.json' }
        ]

```

Let me know if you need anything additional/hit any problems.

**Comment by teddyhwang** [comment]
Thanks for the detailed response. I've followed everything in the guide but the problem is the report does not seem to be accurate. It returns that 0% of the code is covered. Here's an example of the config file i'm working with:

```coffeescript
module.exports = (config) ->
  config.set

    basePath: process.cwd()

    frameworks: [
      'browserify'
      'mocha'
      'chai'
      'chai-sinon'
      'jquery-chai'
      'coffee-coverage'
    ]

    files: [
      'coverage/coverage.js'
      'dist/scripts/app.js' # This has been browserified with browserify-coffee-coverage and it's the main JS that I am testing against
      'tests/client/integration/**/*.coffee'
      'tests/client/unit/**/*.coffee'
    ]

    coffeeCoverage:
      framework:
        initAllSources: true
        sourcesBasePath: 'src/scripts/'
        dest: 'coverage/coverage.js'
        instrumentor: 'istanbul'

    exclude: [ ]

    reporters: [
      'spec'
      'coverage'
    ]

    port: 9876
    colors: true
    logLevel: config.LOG_INFO
    autoWatch: false
    browsers: ['PhantomJS']
    captureTimeout: 60000
    singleRun: true

    preprocessors:
      '**/*{.coffee, .json}': ['browserify']

    browserify: # The tests needs to be browserified
      extensions: ['.coffee']
      transform: ['coffeeify']

    coverageReporter:
      dir: 'coverage'
      reporters: [
        type: 'teamcity'
        subdir: '.'
        file: 'teamcity.txt'
      ,
        type: 'text'
      ,
        type: 'html'
        subdir: '.'
      ]

    browserNoActivityTimeout : 60000
```

The test result output:

```
---------------------------------------|----------|----------|----------|----------|----------------|
All files                              |        0 |        0 |        0 |        0 |                |
---------------------------------------|----------|----------|----------|----------|----------------|
```

**Comment by calvinwiebe** [comment]
Dang. Could you maybe send me an output of the karma run with the `--log-level debug` option set? 

Also make sure that both `coverage.js` and `app.js` look properly instrumented. They should have a bunch of lines such as:
`__coverage__['name/of/file']` etc...

**Comment by calvinwiebe** [comment]
Do 
```
'tests/client/integration/**/*.coffee'
'tests/client/unit/**/*.coffee'
```

call the code in `app.js` globally somehow?

**Comment by teddyhwang** [comment]
Yes - app.js is constructed with the "standalone" option set in browserify so that it's exposed in the global object. I can also confirm that coverage.js and app.js look properly instrumented. Actually, in app.js, I don't see `__coverage__` but instead I see:
```javascript
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
```

Here's a sample output with debug on (no errors shown):

```
  pts-ng-validator: luhn check:
    ✓ should pass luhn check with valid credit card number
    ✓ should fail luhn check with invalid credit card number

PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 323 of 328 (skipped 5) SUCCESS (1 min 32.897 secs / 0.083 secs)
TOTAL: 323 SUCCESS

---------------------------------------|----------|----------|----------|----------|----------------|
File                                   |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------------------------|----------|----------|----------|----------|----------------|
 pts-modules/                          |        0 |      100 |      100 |        0 |                |
  index.coffee                         |        0 |      100 |      100 |        0 |... ,6,7,8,9,11 |
 pts-modules/pts-ng-analytics/src/     |        0 |      100 |        0 |        0 |                |
  pts.analytics.coffee                 |        0 |      100 |        0 |        0 |   1,3,6,8,9,10 |
---------------------------------------|----------|----------|----------|----------|----------------|
All files                              |        0 |        0 |        0 |        0 |                |
---------------------------------------|----------|----------|----------|----------|----------------|
```

**Comment by calvinwiebe** [comment]
Interesting. We definitely do not want the `_$jscoverage` stuff in `app.js`. That is instrumenting it for `jscoverage` reporting, whereas we want `istanbul` coverage to work with `karma-coverage`. `browserify-coffee-coverage` should default to using the `__coverage__` var unless otherwise specified. Can you show me the code/commands for building `app.js`?

**Comment by teddyhwang** [comment]
I used grunt-browserify to compile app.js. Here's the configuration for that:

```coffeescript
browserify =
  coverage:
    files:
      'dist/scripts/app.js': [
        'src/scripts/app.coffee'
      ]
    options:
      browserifyOptions:
        transform: ['browserify-ng-html2js', ['browserify-coffee-coverage', noInit: false]]
        extensions: ['.coffee']
        fullPaths: false
        debug: false
        standalone: 'app'
```

**Comment by calvinwiebe** [comment]
Yep, my bad. Could you add the `instrumentor: istanbul` to the grunt-browserify configuration, like so:
```coffee-script
browserify =
  coverage:
    files:
      'dist/scripts/app.js': [
        'src/scripts/app.coffee'
      ]
    options:
      browserifyOptions:
        transform: ['browserify-ng-html2js', ['browserify-coffee-coverage', { noInit: false, instrumentor: 'istanbul' }]]
        extensions: ['.coffee']
        fullPaths: false
        debug: false
        standalone: 'app'
```

Let me know how that goes.

**Comment by teddyhwang** [comment]
That worked! Though the coverage report is saying that the tests are suspiciously low, that's something I can look into.

Thanks @calvinwiebe you've been very helpful!

**Comment by teddyhwang** [comment]
One additional note that I find interesting. While the coverage is higher than 0%, the report is essentially saying that I have not used any of functions within the files. Is it possible that the blank coverage is overriding the coverage of app.js?

**Comment by calvinwiebe** [comment]
I do not think the blank coverage should override anything. `karma-coverage` should merge all the coverage objects together (adding the counts, as opposed to overriding). In the projects I have used `browserify-coffee-coverage` and `karma-coffee-coverage`, function hits are reported. I wonder what the detailed html report would show for the sources, in your case.

**Comment by teddyhwang** [comment]
Got it. I think everything is working now. Starting to see some accurate results. Will open a new issue if there are any other problems but you can close this one. Thanks again
