### ISSUE TITLE
critical mistake in readme

### ISSUE THREAD

**Issue by Oziabr** [benbria/karma-coffee-coverage#3]
While README.md states:
```
// configure the processor plugin to use `istanbul` style
coffeeCoverage: {
    preprocessors: {
        instrumentor: 'istanbul'
    }
}
```
it should actually be `preprocessor:`, as it is in tests https://github.com/benbria/karma-coffee-coverage/blob/master/test/pluginTest.js#L152

**Comment by calvinwiebe** [comment]
Good catch. Thanks for raising. Fixed in latest master.
